### ISSUE TITLE
CL: IndexOutOfBoundsException: offset(19) should be less than line limit(18)

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#1137]
### Describe the issue
From Crashlytics:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: offset(19) should be less than line limit(18)
       at android.text.TextLine.measure(TextLine.java:353)
       at android.text.Layout.getHorizontal(Layout.java:1225)
       at android.text.Layout.getHorizontal(Layout.java:1202)
       at android.text.Layout.getPrimaryHorizontal(Layout.java:1172)
       at android.text.Layout.getPrimaryHorizontal(Layout.java:1161)
       at androidx.compose.ui.text.android.LayoutHelper.getDownstreamHorizontal(LayoutHelper.kt:353)
       at androidx.compose.ui.text.android.LayoutHelper.getHorizontalPosition(LayoutHelper.kt:236)
       at androidx.compose.ui.text.android.TextLayout.getPrimaryHorizontal(TextLayout.kt:513)
       at androidx.compose.ui.text.android.TextLayout.getBoundingBox(TextLayout.kt:685)
       at androidx.compose.ui.text.AndroidParagraph.getBoundingBox(AndroidParagraph.java:313)
       at androidx.compose.ui.text.MultiParagraph.getBoundingBox(MultiParagraph.java:511)
       at androidx.compose.ui.text.TextLayoutResult.getBoundingBox(TextLayoutResult.kt:527)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.addExtraDataToAccessibilityNodeInfoHelper(AndroidComposeViewAccessibilityDelegateCompat.android.kt:1978)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.access$addExtraDataToAccessibilityNodeInfoHelper(AndroidComposeViewAccessibilityDelegateCompat.java:193)
       at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat$MyNodeProvider.addExtraDataToAccessibilityNodeInfo(AndroidComposeViewAccessibilityDelegateCompat.android.kt:3215)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:1040)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:341)
       at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:75)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1396)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors

- App Version: 
- Android Version:
- Device: (if applies)

**Comment by HonzaR** [comment]
Closing as possibly resolved by some of the previous Jetpack Compose lib updates. It's not seen in the latest Crashlytics reports.
