### ISSUE TITLE
CL: Malformed pattern for ICU DecimalFormat: "##'0'.'00'": Found unquoted special character at position 5

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#1139]
### Describe the issue
From Crashlytics:
```
Fatal Exception: java.lang.IllegalArgumentException: Malformed pattern for ICU DecimalFormat: "##'0'.'00'": Found unquoted special character at position 5
       at android.icu.impl.number.PatternStringParser$ParserState.toParseException(PatternStringParser.java:269)
       at android.icu.impl.number.PatternStringParser.consumePattern(PatternStringParser.java:286)
       at android.icu.impl.number.PatternStringParser.parseToPatternInfo(PatternStringParser.java:30)
       at android.icu.impl.number.PatternStringParser.parseToExistingPropertiesImpl(PatternStringParser.java:587)
       at android.icu.impl.number.PatternStringParser.parseToExistingProperties(PatternStringParser.java:79)
       at android.icu.text.DecimalFormat.setPropertiesFromPattern(DecimalFormat.java:2436)
       at android.icu.text.DecimalFormat.applyPattern(DecimalFormat.java:465)
       at android.icu.text.DecimalFormat.applyLocalizedPattern(DecimalFormat.java:489)
       at java.text.DecimalFormat.applyLocalizedPattern(DecimalFormat.java:3756)
       at cash.z.ecc.sdk.extension.PercentDecimalExtKt.preparePercentDecimalFormat(PercentDecimalExt.kt:19)
       at cash.z.ecc.sdk.extension.PercentDecimalExtKt.toPercentageWithDecimal-ac8RlKg$default(PercentDecimalExt.kt:11)
       at co.electriccoin.zcash.ui.screen.account.model.WalletDisplayValues$Companion.getNextValues$ui_lib_release(WalletDisplayValues.java:60)
       at co.electriccoin.zcash.ui.screen.account.view.AccountViewKt.Status(AccountView.kt:153)
       at co.electriccoin.zcash.ui.screen.account.view.AccountViewKt.AccountMainContent(AccountView.kt:126)
       at co.electriccoin.zcash.ui.screen.account.view.AccountViewKt.access$AccountMainContent(AccountView.kt:1)
       at co.electriccoin.zcash.ui.screen.account.view.AccountViewKt$Account$2.invoke(AccountView.kt:70)
       at co.electriccoin.zcash.ui.screen.account.view.AccountViewKt$Account$2.invoke(AccountView.kt:69)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:117)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
       at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:239)
       at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1$bodyContentPlaceables$1.invoke(Scaffold.kt:221)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(LayoutNodeSubcompositionsState.java:1067)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$subcompose$3$1$1.invoke(LayoutNodeSubcompositionsState.java:701)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:108)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
       at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm_jvm.kt:78)
       at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3340)
       at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3273)
       at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:588)
       at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1013)
       at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:4007)
       at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:4007)
       at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:4007)
       at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:520)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(SubcomposeLayout.kt:721)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:694)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:685)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(LayoutNodeSubcompositionsState.java:669)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1014)
       at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:221)
       at androidx.compose.material3.ScaffoldKt$ScaffoldLayout$1$1$1.invoke(Scaffold.kt:128)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:879)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.java:365)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.java:357)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2299)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
       at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:683)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2299)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:656)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
       at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:225)
       at androidx.compose.foundation.layout.BoxKt.placeInBox(Box.kt:185)
       at androidx.compose.foundation.layout.BoxKt.access$placeInBox(Box.kt:1)
       at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:125)
       at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1$measure$2.invoke(Box.kt:124)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.java:365)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.java:357)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2299)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
       at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:473)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:288)
       at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(SimpleGraphicsLayerModifier.java:648)
       at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(SimpleGraphicsLayerModifier.java:647)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:172)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:476)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:685)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2299)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeAt-f8xVGno(LayoutNodeLayoutDelegate.kt:656)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer-aW-9-wM(Placeable.kt:460)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelativeWithLayer-aW-9-wM$default(Placeable.kt:245)
       at androidx.compose.foundation.pager.MeasuredPage.place(MeasuredPage.java:106)
       at androidx.compose.foundation.pager.PagerMeasureKt$measurePager$6.invoke(PagerMeasure.kt:394)
       at androidx.compose.foundation.pager.PagerMeasureKt$measurePager$6.invoke(PagerMeasure.kt:392)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.foundation.pager.PagerMeasureResult.placeChildren(PagerMeasureResult.kt:2)
       at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:879)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.java:365)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$layoutChildren$1$1.invoke(LayoutNodeLayoutDelegate.java:357)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2299)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutSnapshotReads$ui_release(OwnerSnapshotObserver.kt:83)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.layoutChildren(LayoutNodeLayoutDelegate.kt:357)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.onNodePlaced$ui_release(LayoutNodeLayoutDelegate.kt:493)
       at androidx.compose.ui.node.InnerNodeCoordinator.placeAt-f8xVGno(InnerNodeCoordinator.kt:160)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.place(Placeable.kt:447)
       at androidx.compose.ui.layout.Placeable$PlacementScope.place$default(Placeable.kt:213)
       at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$2$1.invoke(AndroidOverscroll.kt:583)
       at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$2$1.invoke(AndroidOverscroll.kt:582)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:172)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:473)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:288)
       at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1$1.invoke(AndroidOverscroll.kt:571)
       at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1$1.invoke(AndroidOverscroll.kt:564)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:172)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:473)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:288)
       at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(SimpleGraphicsLayerModifier.java:648)
       at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(SimpleGraphicsLayerModifier.java:647)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:172)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:444)
       at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:201)
       at androidx.compose.foundation.layout.PaddingNode$measure$1.invoke(PaddingNode.java:403)
       at androidx.compose.foundation.layout.PaddingNode$measure$1.invoke(PaddingNode.java:401)
       at androidx.compose.ui.layout.Placeable$PlacementScope$Companion.executeWithRtlMirroringValues(Placeable.java:373)
       at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:52)
       at androidx.compose.ui.node.LayoutModifierNodeCoordinator.placeAt-f8xVGno(LayoutModifierNodeCoordinator.kt:172)
       at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.java:34)
       at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:450)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:683)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate$placeOuterCoordinator$1.invoke(LayoutNodeLayoutDelegate.kt:678)
       at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.java:2299)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
       at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
       at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:98)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.placeOuterCoordinator-f8xVGno(LayoutNodeLayoutDelegate.kt:678)
       at androidx.compose.ui.node.LayoutNode.onDensityOrLayoutDirectionChanged(LayoutNode.kt:703)
       at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.replace(LayoutNodeLayoutDelegate.java:703)
       at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:910)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:469)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$getRoot$p(MeasureAndLayoutDelegate.kt:39)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:39)
       at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:344)
       at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:879)
       at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:223)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1127)
       at android.view.View.draw(View.java:23892)
       at android.view.View.updateDisplayListIfDirty(View.java:22756)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
       at android.view.View.updateDisplayListIfDirty(View.java:22712)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
       at android.view.View.updateDisplayListIfDirty(View.java:22712)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
       at android.view.View.updateDisplayListIfDirty(View.java:22712)
       at android.view.View.draw(View.java:23620)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4556)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4317)
       at android.view.View.draw(View.java:23892)
       at com.android.internal.policy.DecorView.draw(DecorView.java:809)
       at android.view.View.updateDisplayListIfDirty(View.java:22756)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
       at android.view.Choreographer.doCallbacks(Choreographer.java:952)
       at android.view.Choreographer.doFrame(Choreographer.java:882)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors

- App Version: 
- Android Version:
- Device: (if applies)

**Comment by HonzaR** [comment]
Reopening as this bug happened again in https://github.com/Electric-Coin-Company/zashi-android/pull/1408 in `test_android_modules_wtf_no_coverage` CI check.

**Comment by HonzaR** [comment]
Closing, wrong issue. This is supposed to be reopened https://github.com/Electric-Coin-Company/zashi-android/issues/1180.
