### ISSUE TITLE
Failed to parse checkpoint file 

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#1180]
### Describe the issue
Sometimes, there is an occasional bug reported by our screenshot test running on CI (exclusively). It refers to the birthday checkpoint parsing

#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors
```
cash.z.ecc.android.sdk.exception.BirthdayException$MalformattedBirthdayFilesException: Failed to parse file co.electriccoin.zcash/checkpoint/mainnet/419200.json verify that it is formatted as #####.json, where the first portion is an Int representing the height of the tree contained in the file
at cash.z.ecc.android.sdk.tool.CheckpointTool.getFirstValidWalletBirthday$zcash_android_sdk_2_0_4_release(CheckpointTool.kt:164)
at cash.z.ecc.android.sdk.tool.CheckpointTool$getFirstValidWalletBirthday$1.invokeSuspend(Unknown Source:18)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:234)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6e198a6, Dispatchers.Main]
Caused by: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled
```

- App Version: 
- Android Version:
- Device: (if applies)

### Any extra information that might be useful in the debugging process.

It usually succeeds when the CI is rerun.

**Comment by HonzaR** [comment]
Reopening this as it occurred in https://github.com/Electric-Coin-Company/zashi-android/pull/1408 in `test_android_modules_wtf_no_coverage` CI check again. Note that we are experiencing this only in the CI check.
