### ISSUE TITLE
Put UTXOs Rust error: `Network type mismatch`

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#1656]
## Describe the solution you'd like

- [x] Add a new check on the network type into the related Rust method
- [x] Turn SDK proguard off for the next release to test its behavior
- [x] Add a new line with Network Type to the email template so we’re 100% sure that the Zashi built-in network type is correct
- [x] Test sending from Kraken account for us to test sending from them to Zashi

## Additional context
```
java.lang.RuntimeException: Error while inserting UTXO: Data DB is corrupted: Network type mismatch
at cash.z.ecc.android.sdk.internal.jni.RustBackend.putUtxo(Native Method)
at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$putUtxo(Unknown Source:0)
at cash.z.ecc.android.sdk.internal.jni.RustBackend$putUtxo$2.invokeSuspend(Unknown Source:30)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:920)
```

Internal resources:
- https://linear.app/zcash/issue/PRO-278/[bug]-a-user-experiences-a-syncing-error-due-to-unsupported-address
- https://zcash.slack.com/archives/C02C1GZ0R6F/p1729702935021489

**Comment by HonzaR** [comment]
Sending transparent funds from a Kraken account to a Zashi wallet did not cause problems and worked as expected.

**Comment by HonzaR** [comment]
Closing this this is waits for the latest Rust crates bump in SDK.
