### ISSUE TITLE
Screenshot test on Send with pseudolocales problem

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zashi-android#817]
### Describe the issue
We have a bug in our screenshot test with pseudolocales texts. The problem applies to both `ar_XB` and `en_XA` on Send screen. The problematic part seems to be the `Amount` field validation on `Send.Form` screen in these pseudolocales.

The trouble was probably always present, but hidden by taking a screenshot of the same screen and not the subsequent `Send.Confirm` screen, as the Send button was disabled by the validation and screenshot flow was then blocked the `Send.Form` screen.

### Expected behavior
Now, after adding next Send subscreens e.g. Sending, SendFailure or SendSuccessful we'd like to move to these subscreens with the screenshot test too, but we can't. Taking screenshots on these screens is commented out for now.

### Actual behavior + errors
```
java.lang.AssertionError: Failed to inject touch input.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains '‏‮Press‬‏ ‏‮to‬‏ ‏‮send‬‏ ‏‮ZEC‬‏' (ignoreCase: false))

at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:79)
at androidx.compose.ui.test.ActionsKt.performTouchInput(Actions.kt:358)
at androidx.compose.ui.test.Actions_androidKt.performClickImpl(Actions.android.kt:20)
at androidx.compose.ui.test.ActionsKt.performClick(Actions.kt:51)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTestKt.sendZecScreenshots(ScreenshotTest.kt:538)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTestKt.access$sendZecScreenshots(ScreenshotTest.kt:1)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTest.take_screenshots_for_new_wallet_and_rest_of_app(ScreenshotTest.kt:247)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTest.access$take_screenshots_for_new_wallet_and_rest_of_app(ScreenshotTest.kt:81)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTest$take_screenshots_for_new_wallet_and_rest_of_app_light_ar_XB$1.invoke(ScreenshotTest.kt:212)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTest$take_screenshots_for_new_wallet_and_rest_of_app_light_ar_XB$1.invoke(ScreenshotTest.kt:211)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTest.runWith(ScreenshotTest.kt:108)
at co.electroniccoin.zcash.ui.screenshot.ScreenshotTest.take_screenshots_for_new_wallet_and_rest_of_app_light_ar_XB(ScreenshotTest.kt:211)
```

**Comment by HonzaR** [comment]
After the latest analyses, we know that the trouble is in the pseudo-locales. It's the `continuous_filter` and `confirm_filter` string resources in the SDK, which are changed while they're read in the screenshot test with one of the pseudo-locales set. We currently support both the `en-XA` and `ar-XB`. 

The original regex pattern is:
`^([0-9]*([0-9]+([,]$|[,][0-9]+))*([.]$|[.][0-9]+)?)?$`
But in the en-XA it's:
`^([0-9]*([0-9]+([,]€|[,][0-9]+))*([.]€|[.][0-9]+)¿)¿€ one two three four five six seven eight nine ten eleven`
And in the ar-XB it's:
`^([0-9]*([0-9]+([‏,‏]$|[‏,‏][0-9]+))*([‏.‏]$|[‏.‏][0-9]+)?)?$`

I tried to prepare these regex patterns in the related string resources `values-xa` and its modifications, but none of it worked, probably because we work with pseudol-ocales here.

The only thing which worked for me was to mark the string resource as non-translatable with `translatable="false"`, but we'd break our intention of having the regex changed in other locales with it.
